services:
  blue-app:
    build: .
    container_name: blue-app
    environment:
      - ENVIRONMENT=blue
    ports:
      - "127.0.0.1:8081:80"
    restart: unless-stopped
    networks:
      - frontend

  green-app:
    build: .
    container_name: green-app
    environment:
      - ENVIRONMENT=green
    ports:
      - "127.0.0.1:8082:80"
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
